In [5]:
import numpy as np

b = np.arange(3).reshape(3,1)
print(b)

[[0]
 [1]
 [2]]


### Broadcasting

In [19]:
import numpy as np
M = np.ones((2,3))
a = np.arange(3)

print(M)
print(a)
print(M.ndim)
print(a.ndim)
print(M.shape)
print(a.shape)

print()
print(a+M) #Broadcasting

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
2
1
(2, 3)
(3,)

[[1. 2. 3.]
 [1. 2. 3.]]


Above case: F
    Rule 1: Dimensions are not same, so it converted to two dimension.
    Rule 2: Shape is not same, so it will go to Rule 3
    Rule 3: If there is any dimension 1, then it will add the duplicate the row and form same shape. then add.

In [22]:
a = np.arange(12).reshape(2,6)
b = np.arange(6).reshape(2,3)

print(a.shape)
print(b.shape)
print('It will fail as though they have same dimensions, they dont have shape. It will go for Rule 3. Any dimension has 1 ? as there are no. It will throw error')

#print(a+b)

(2, 6)
(2, 3)
It will fail as though they have same dimensions, they dont have shape. It will go for Rule 3. Any dimension has 1 ? as there are no. It will throw error


In [32]:
# Working with Boolean Array

rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))

print('Original Array : \n',x)

print('It will broadcast singlevector to similar shape and dimension and then perform vectorization')

print('no of elements less than 6:',np.sum(x<6))
print('no of elements less than 6 in each column:',np.sum(x<6, axis=0))
print('no of elements less than 6 in each row:',np.sum(x<6, axis=1))

Original Array : 
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
It will broadcast singlevector to similar shape and dimension and then perform vectorization
no of elements less than 6: 8
no of elements less than 6 in each column: [2 2 2 2]
no of elements less than 6 in each row: [4 2 2]


In [31]:
#Random int generator
rng = np.random.RandomState(5)
x = rng.randint(10, size=(4,4))
print('Original Array : \n',x)

Original Array : 
 [[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]
 [5 7 0 1]]


In [38]:
# any() and all()
print('Original Matrix:\n',x)
print('\n',np.any(x<8))
print(np.all(x>10))

print('on x-axis:',np.any(x<8, axis=0))
print('on y-axis:',np.any(x<8, axis=1))

Original Matrix:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

 True
False
on x-axis: [ True  True  True  True]
on y-axis: [ True  True  True]


In [48]:
arr = np.arange(8)
print('Array:',arr)
print('Array Dimension:',arr.ndim)

print('Reshaped array:\n',arr.reshape(4,2))

# We can reshape multidimensional arrays too
print('Reshaped array:\n',arr.reshape(4,2).reshape(2,4))
print('Reshaped array:\n',arr.reshape(4,2).reshape(8,1))
print('Reshaped array:\n',arr.reshape(4,2).reshape(2,2,2))

Array: [0 1 2 3 4 5 6 7]
Array Dimension: 1
Reshaped array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Reshaped array:
 [[0 1 2 3]
 [4 5 6 7]]
Reshaped array:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
Reshaped array:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [54]:
arr = np.arange(15)

print('1D array:\n',arr)

print("5 rows: \n",arr.reshape((5,-1))) # if we give -1, it will be internally computed

print("5 columns: \n",arr.reshape((-1,5)))

print("5 columns: \n",np.arange(16).reshape((-1,2,2)))


1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
5 rows: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
5 columns: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
5 columns: 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [61]:
# ravel() and flatten()

arr = np.arange(15).reshape(5,3)
print(arr.ndim)
print('Array:\n',arr)

#ravel doesn't produce a copy of the underlying data whereas the flatten methods always returns a copy of the data
rav = arr.ravel()
print('Ravel Array:\n',rav)

flat = arr.flatten()
print('Flatten Array:\n',flat)

# Checking the diff
arr[1,1] = 100
print(arr)
print(rav)
print(flat)


2
Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Ravel Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Flatten Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[  0   1   2]
 [  3 100   5]
 [  6   7   8]
 [  9  10  11]
 [ 12  13  14]]
[  0   1   2   3 100   5   6   7   8   9  10  11  12  13  14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### Concatenation

In [72]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
print(arr1)
print(arr2)

print('Row wise:\n',np.concatenate([arr1,arr2],axis = 0))
print('Col wise:\n',np.concatenate([arr1,arr2],axis = 1))

print('--------------------------------------')
print('Similar to rbind and cbind, we have vstack and hstack\n')
print('Vertical Stack:\n',np.vstack((arr1,arr2)))
print('Horizontal Stack:\n',np.hstack((arr1,arr2)))



[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
Row wise:
 [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
Col wise:
 [[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
--------------------------------------
Similar to rbind and cbind

Vertical Stack:
 [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack:
 [[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


## Fancy Indexing

In [80]:
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)
ind = [2,4,5]
print(x[ind])

ind= np.array([[2,4],[3,6]])
print(x[ind])

[51 92 14 71 60 20 82 86 74 74]
[14 60 20]
[[14 60]
 [71 82]]


## Numpy Structured Arrays